<a href="https://colab.research.google.com/github/PDavid413/PL_1142/blob/main/%E3%80%8CHW1_%E6%97%A5%E5%B8%B8%E6%94%AF%E5%87%BA%E9%80%9F%E7%AE%97%E8%88%87%E5%88%86%E6%94%A4_ipynb%E3%80%8D%E7%9A%84%E5%89%AF%E6%9C%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#日常支出速算與分攤（作業一）
- 目標：從 Sheet 讀「消費紀錄」→ 計總額/分類小計/AA 分攤 → 寫回 Sheet Summary 分頁。
- AI 點子（可選）：請模型總結本週花錢習慣與建議（例如「外食過多」）。
- Sheet 欄位：date, category, item, amount, payer

GoogleSheet: https://docs.google.com/spreadsheets/d/13QhkkY9mNQYrr6i3jq7Iz2zXgeLAYlfHo6Wqw_KkfJM/edit?usp=sharing

In [ ]:
from google.colab import auth
auth.authenticate_user()

import gspread
from google.auth import default
creds, _ = default()

gc = gspread.authorize(creds)

In [ ]:
import pandas as pd
# read data and put it in a dataframe
# 在 google 工作表載入 gsheets
gsheets = gc.open_by_url('https://docs.google.com/spreadsheets/d/13QhkkY9mNQYrr6i3jq7Iz2zXgeLAYlfHo6Wqw_KkfJM/edit?usp=sharing')

In [ ]:
# 從 gsheets 的 All-whiteboard-device 載入 sheets
sheets = gsheets.worksheet('工作表1').get_all_values()
# 將 sheets1 資料載入 pd 的 DataFrame 進行分析
df = pd.DataFrame(sheets[1:], columns=sheets[0])
# 取得最前面的5筆資料
df.head()

Empty DataFrame
Columns: []
Index: []

In [ ]:
import datetime

In [ ]:
# 讓使用者輸入資料
user_str = input("請輸入購買者名稱")
date_str = input("請輸入日期 (格式：YYYY-MM-DD): ")
# 檢查日期格式是否正確
datetime.datetime.strptime(date_str, '%Y-%m-%d')

time_str = input("請輸入時間 (格式：HH:MM): ")
# 檢查時間格式是否正確
datetime.datetime.strptime(time_str, '%H:%M')

item = input("請輸入品項: ")
amount = float(input("請輸入金額: "))
category = int(input("請輸入消費類型(1=食物,2=娛樂,3=交通,4=日常用品,5=其他): "))
if (category == 1):
  ccode = "食物"
elif (category == 2):
  ccode = "娛樂"
elif (category == 3):
  ccode = "交通"
elif (category == 4):
  ccode = "日常用品"
elif (category == 5):
  ccode = "其他"

請輸入購買者名稱cc
請輸入日期 (格式：YYYY-MM-DD): 2026-03-04
請輸入時間 (格式：HH:MM): 08:15
請輸入品項: box cutter
請輸入金額: 200
請輸入消費類型(1=食物,2=娛樂,3=交通,4=日常用品,5=其他): 4

In [ ]:
date_str

'2026-03-05'

In [ ]:
time_str

'12:30'

In [ ]:
item

'burger'

In [ ]:
amount

120.0

In [ ]:
user_str

'aa'

In [ ]:
ccode

'食物'

In [ ]:
# 創建一個新的 DataFrame 來代表你要新增的資料
new_data = pd.DataFrame([{
    '日期': date_str,
    '時間': time_str,
    '品項': item,
    '金額': amount,
    '使用者': user_str,
    '消費類型': ccode,
}])

# 使用 concat() 將新資料合併到舊的 df 中
df = pd.concat([df, new_data], ignore_index=True)

In [ ]:
df

           日期     時間            品項     金額 使用者  消費類型
0  2026-03-05  12:10        burger   89.0  aa    食物
1  2026-03-03  12:30  metro ticket   50.0  bb    交通
2  2026-03-04  08:15    box cutter  200.0  cc  日常用品

In [ ]:
# 將 DataFrame 的欄位名稱作為第一列
headers = df.columns.tolist()

# 將 DataFrame 的資料轉換成列表的列表
data_rows = df.values.tolist()

# 第一步：取得工作表物件
worksheet = gsheets.worksheet('工作表1')

# 第二步：清空整個工作表，確保沒有舊的或重複的資料
worksheet.clear()

# 第三步：將欄位名稱和資料行合併，並寫入工作表
# 由於已經清空，所以總是包含標頭
data_to_write = [headers] + data_rows
worksheet.append_rows(values=data_to_write, value_input_option='USER_ENTERED')
print("資料已成功寫入 Google 工作表！")

資料已成功寫入 Google 工作表！